services:
  - type: web
    name: CodeReadApp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    build:
      packages:
        - wkhtmltopdf
